format = """
[┌╴<](bright-purple)[$username in $hostname $os](bright-purple)[>](bold bright-purple) $directory$git_branch$git_commit
[└─](bright-purple) $character\
"""

# シェルのプロンプトの間に空行を挿入する
add_newline = true

# 記号"❯"を記号"➜"に置き換える
[character] # 設定対象のモジュール名は 'character'
success_symbol = "[\\$](bright-purple)"
error_symbol = "[x](bold red)"
vimcmd_symbol = "[\\$](bright-purple)"

[directory]
style='bold bright-green'

# パッケージ別

[git_commit]
tag_symbol = "\\($hash$tag\\)"

[git_status]
ahead = ">"
behind = "<"
diverged = "<>"
renamed = "r"
deleted = "x"

[os]
disabled = false
style = "bg:color_orange fg:color_fg0"

[os.symbols]
Windows = "Windows"
Ubuntu = "Ubuntu "
SUSE = "SUSE"
Raspbian = "Raspbian "
Mint = "Mint"
Macos = "MacOS"
Manjaro = "Manjaro"
Linux = "Linux"
Gentoo = "Gentoo"
Fedora = "Fedora"
Alpine = "Alpine"
Amazon = "Amazon"
Android = "Android"
Arch = "Arch"
Artix = "Artix"
EndeavourOS = "EndeavourOS"
CentOS = "CentOS"
Debian = "Debian"
Redhat = "RedHat"
RedHatEnterprise = "RHEL"
Pop = "Pop"

[hostname]
ssh_only=false
ssh_symbol=' via ssh'
style='bold bright-blue'
format='[$hostname$ssh_symbol]($style)'

[username]
show_always=true
style_user='bold bright-blue'
style_root='bold red'
format='[$user]($style)'
